# Generated by Django 2.0.6 on 2018-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0004_auto_20180617_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
