# Generated by Django 2.0.6 on 2018-06-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
