# Generated by Django 2.0.6 on 2018-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcriber', '0002_subcriber_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriber',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
