# Generated by Django 2.0.6 on 2018-06-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20180615_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
    ]
