# Generated by Django 2.0.6 on 2018-06-15 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20180615_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='datetime',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
