# Generated by Django 2.0.6 on 2018-06-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20180616_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=3),
        ),
    ]
