# Generated by Django 2.0.6 on 2018-06-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20180616_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchevent',
            old_name='event',
            new_name='event_type',
        ),
    ]
