# Generated by Django 2.0.6 on 2018-06-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20180617_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ('match', 'time')},
        ),
    ]
